"""Official dispatch names and observable SDK coverage groups."""

from .http_catalog import HTTP_TARGETS, Endpoint


EVENT_FAMILIES = {
    "GUILDS": (0, "GUILD_CREATE GUILD_UPDATE GUILD_DELETE CHANNEL_CREATE CHANNEL_UPDATE CHANNEL_DELETE"),
    "GUILD_MEMBERS": (1, "GUILD_MEMBER_ADD GUILD_MEMBER_UPDATE GUILD_MEMBER_REMOVE"),
    "GUILD_MESSAGES": (9, "MESSAGE_CREATE MESSAGE_DELETE"),
    "GUILD_MESSAGE_REACTIONS": (10, "MESSAGE_REACTION_ADD MESSAGE_REACTION_REMOVE"),
    "DIRECT_MESSAGE": (12, "DIRECT_MESSAGE_CREATE DIRECT_MESSAGE_DELETE"),
    "OPEN_FORUM_EVENT": (18, "OPEN_FORUM_THREAD_CREATE OPEN_FORUM_THREAD_UPDATE OPEN_FORUM_THREAD_DELETE OPEN_FORUM_POST_CREATE OPEN_FORUM_POST_DELETE OPEN_FORUM_REPLY_CREATE OPEN_FORUM_REPLY_DELETE"),
    "AUDIO_OR_LIVE_CHANNEL_MEMBER": (19, "AUDIO_OR_LIVE_CHANNEL_MEMBER_ENTER AUDIO_OR_LIVE_CHANNEL_MEMBER_EXIT"),
    "GROUP_MEMBER_EVENT": (24, "GROUP_MEMBER_ADD GROUP_MEMBER_REMOVE GROUP_JOIN_REQUEST"),
    "GROUP_AND_C2C_EVENT": (25, "C2C_MESSAGE_CREATE FRIEND_ADD FRIEND_DEL C2C_MSG_REJECT C2C_MSG_RECEIVE GROUP_AT_MESSAGE_CREATE GROUP_MESSAGE_CREATE GROUP_ADD_ROBOT GROUP_DEL_ROBOT GROUP_MSG_REJECT GROUP_MSG_RECEIVE SUBSCRIBE_MESSAGE_STATUS"),
    "INTERACTION": (26, "INTERACTION_CREATE"),
    "MESSAGE_AUDIT": (27, "MESSAGE_AUDIT_PASS MESSAGE_AUDIT_REJECT"),
    "FORUMS_EVENT": (28, "FORUM_THREAD_CREATE FORUM_THREAD_UPDATE FORUM_THREAD_DELETE FORUM_POST_CREATE FORUM_POST_DELETE FORUM_REPLY_CREATE FORUM_REPLY_DELETE FORUM_PUBLISH_AUDIT_RESULT"),
    "AUDIO_ACTION": (29, "AUDIO_START AUDIO_FINISH AUDIO_ON_MIC AUDIO_OFF_MIC"),
    "PUBLIC_GUILD_MESSAGES": (30, "AT_MESSAGE_CREATE PUBLIC_MESSAGE_DELETE"),
}

EVENT_INTENTS = {name: 1 << bit for bit, names in EVENT_FAMILIES.values() for name in names.split()}
CONNECTION_EVENTS = frozenset({"READY", "RESUMED"})
EVENT_NAMES = frozenset(EVENT_INTENTS) | CONNECTION_EVENTS
